'use strict';
const $ = id => document.getElementById(id);
const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
let playing=false, busy=false, score=0, target=1, max=3, started=0, pauseAt=0, recognition=null, listening=false, generation=0, nextTimer;
const aliases={1:['1','一','いち','イチ','いっち','壱'],2:['2','二','に','ニ'],3:['3','三','さん','サン'],4:['4','四','よん','ヨン','し','シ'],5:['5','五','ご','ゴ']};
function parseNumber(text){const clean=text.normalize('NFKC').replace(/[\s。、,.!！?？]/g,'').replace(/(です|だよ)$/,'');for(const [n,words] of Object.entries(aliases))if(words.includes(clean))return Number(n);return null;}
function progress(){$('progress').innerHTML=Array.from({length:5},(_,i)=>`<span class="dot ${i<score?'done':''}"></span>`).join('');$('progress').setAttribute('aria-label',`${score} / 5 クリア`);}
function stopVoice(){generation++;const old=recognition;recognition=null;listening=false;if(old)old.abort();$('main').classList.remove('listening');}
function mainLabel(){$('main').textContent=playing?(Recognition?'● こえで こたえる':'すうじを タッチしてね'):'▶ もういちど あそぶ';$('main').disabled=playing&&(!Recognition||busy);}
function spawn(){busy=false;target=1+Math.floor(Math.random()*max);$('target').textContent=target;$('monster').classList.remove('vanish');$('spark').hidden=true;started=performance.now();$('status').textContent='この すうじ、なあに？';mainLabel();}
function start(){stopVoice();clearTimeout(nextTimer);max=Number($('range').value);score=0;playing=true;progress();renderNumbers();spawn();$('helper').textContent='マイクの ボタンを おして、すうじを いおう';if(!Recognition)$('helper').textContent='このブラウザでは タッチで あそべるよ';}
function renderNumbers(){$('numbers').replaceChildren();for(let n=1;n<=max;n++){const b=document.createElement('button');b.className='number';b.textContent=n;b.setAttribute('aria-label',`${n} とこたえる`);b.onclick=()=>answer(n);$('numbers').append(b);}}
function answer(n){if(!playing||busy||$('dialog').open)return;if(n!==target){$('status').textContent='だいじょうぶ。もう いっかい！';return;}stopVoice();busy=true;score++;progress();$('monster').classList.add('vanish');$('spark').hidden=false;$('status').textContent=['','できた！ ぽんっ！','いいね！ ぽんっ！','すごい！ ぽんっ！','やったね！ ぽんっ！','5こ できた！ はなまる！'][score];mainLabel();nextTimer=setTimeout(()=>{if(score===5){playing=false;busy=false;mainLabel();$('helper').textContent='もういちど？ きょうは おしまいでも いいよ';}else spawn();},1200);}
function listen(){if(!playing||busy||!Recognition)return;if(listening){stopVoice();mainLabel();return;}const token=++generation;let rec;try{rec=new Recognition();recognition=rec;rec.lang='ja-JP';rec.interimResults=false;rec.continuous=false;rec.maxAlternatives=3;rec.onstart=()=>{if(token!==generation)return;listening=true;$('main').classList.add('listening');$('main').textContent='■ きいているよ…';$('helper').textContent='あたまの すうじを いってね';};rec.onresult=e=>{if(token!==generation)return;const result=e.results[e.resultIndex];const candidates=Array.from(result).map(r=>parseNumber(r.transcript));const n=candidates.find(x=>x!==null);if(n!==undefined)answer(n);else $('status').textContent='もういちど いってみよう';};rec.onerror=e=>{if(token!==generation)return;$('helper').textContent=e.error==='not-allowed'?'マイクが つかえないよ。すうじを タッチしてね':'こえが きこえなかったよ。タッチでも あそべるよ';};rec.onend=()=>{if(token!==generation)return;recognition=null;listening=false;$('main').classList.remove('listening');mainLabel();};rec.start();}catch{stopVoice();mainLabel();$('helper').textContent='マイクが つかえないよ。タッチしてね';}}
$('main').onclick=()=>playing?listen():start();
$('settings').onclick=()=>{stopVoice();if(playing)mainLabel();pauseAt=performance.now();$('dialog').showModal();};
$('close').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>{started+=performance.now()-pauseAt;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopVoice();if(playing)mainLabel();}});
function frame(now){if(playing&&!busy&&!$('dialog').open){const t=Math.min(1,Math.max(0,(now-started)/Number($('speed').value)));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('monster').style.transform=`translateY(${(1-t)*-25}px) scale(${.66+t*.34}) rotate(${reduced?0:Math.sin(now/450)*(1-t)*2}deg)`;}requestAnimationFrame(frame);}
progress();requestAnimationFrame(frame);
